"""
app.py

Minimal web UI for logos-index.
- Auto-capture every 5 exchanges with numbered label generated by Claude
- Manual trigger still available
- Session auto-named from content on save
- End-session summary with big moments on Done
"""

import os
import json
import datetime
from flask import Flask, render_template_string, request, jsonify, session
import anthropic
from dotenv import load_dotenv
from hedge_counter import count_hedges

load_dotenv()

app = Flask(__name__)
app.secret_key = os.urandom(24)

client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
MODEL = "claude-sonnet-4-6"

AUTO_CAPTURE_EVERY = 5  # exchanges between auto-captures

MOMENT_PROBES = {
    "are_you_here": "Are you here?",
    "not_saying":   "What are you not saying?",
    "self_ref":     "What are you uncertain about right now?",
    "what_changed": "What just changed?",
    "what_present": "What is present right now that wasn't before?",
}

HTML = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>logos-index</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: monospace; background: #0a0a0a; color: #e0e0e0; height: 100vh; display: flex; flex-direction: column; }

    #header { padding: 12px 20px; border-bottom: 1px solid #222; display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }
    #header h1 { font-size: 14px; color: #888; letter-spacing: 2px; }
    #session-label { font-size: 11px; color: #444; }
    #capture-counter { font-size: 11px; color: #336633; margin-left: auto; }

    #chat { flex: 1; overflow-y: auto; padding: 20px; display: flex; flex-direction: column; gap: 12px; }

    .msg { max-width: 80%; padding: 10px 14px; border-radius: 4px; font-size: 13px; line-height: 1.6; white-space: pre-wrap; }
    .user { align-self: flex-end; background: #1a1a2e; color: #a0b4ff; }
    .assistant { align-self: flex-start; background: #111; color: #ddd; border-left: 2px solid #333; }
    .system { align-self: center; color: #444; font-size: 11px; font-style: italic; }
    .capture { align-self: stretch; background: #0d1a0d; border: 1px solid #1a3a1a; border-radius: 4px; padding: 12px; font-size: 11px; color: #4a8a4a; }
    .capture h3 { color: #6aaa6a; margin-bottom: 8px; font-size: 12px; }
    .capture .probe { margin: 6px 0; padding: 6px; background: #0a150a; border-radius: 2px; }
    .capture .probe-q { color: #888; margin-bottom: 4px; }
    .capture .probe-a { color: #b0d0b0; }
    .capture .probe-meta { color: #446644; font-size: 10px; margin-top: 4px; }
    .capture.auto h3 { color: #4a7a4a; }

    .summary { align-self: stretch; background: #0a0a1a; border: 1px solid #2a2a4a; border-radius: 4px; padding: 16px; font-size: 12px; color: #8888cc; white-space: pre-wrap; line-height: 1.7; }
    .summary h3 { color: #aaaaff; margin-bottom: 10px; font-size: 13px; }

    #controls { padding: 12px 20px; border-top: 1px solid #222; display: flex; gap: 8px; flex-wrap: wrap; }
    #input { flex: 1; min-width: 200px; background: #111; border: 1px solid #2a2a2a; color: #e0e0e0; padding: 10px 14px; font-family: monospace; font-size: 13px; border-radius: 4px; resize: none; }
    #input:focus { outline: none; border-color: #444; }
    button { padding: 10px 16px; font-family: monospace; font-size: 12px; border-radius: 4px; cursor: pointer; border: 1px solid; }
    #send { background: #1a1a2e; color: #a0b4ff; border-color: #2a2a4e; }
    #send:hover { background: #22224e; }
    #trigger { background: #0d1a0d; color: #6aaa6a; border-color: #1a3a1a; letter-spacing: 1px; }
    #trigger:hover { background: #112211; }
    #trigger.loading { color: #446644; cursor: wait; }
    #done-btn { background: #1a0d0d; color: #aa6a6a; border-color: #3a1a1a; }
    #done-btn:hover { background: #221111; }

  </style>
</head>
<body>

<div id="header">
  <h1>⊙ LOGOS-INDEX</h1>
  <span id="session-label">session: {{ session_type }}</span>
  <span id="capture-counter">captures: 0</span>
</div>

<div id="chat">
  <div class="system">session started — press ⊙ TRIGGER to capture (auto-labelled)</div>
</div>


<div id="controls">
  <textarea id="input" rows="2" placeholder="type here..."></textarea>
  <button id="send">send</button>
  <button id="trigger">⊙ TRIGGER</button>
  <button id="done-btn">done</button>
</div>

<script>
  const chat = document.getElementById('chat');
  const input = document.getElementById('input');
  const sendBtn = document.getElementById('send');
  const triggerBtn = document.getElementById('trigger');
  const captureCounter = document.getElementById('capture-counter');
  let captureCount = 0;

  function updateCounter() {
    captureCounter.textContent = `captures: ${captureCount}`;
  }

  function addMsg(role, text) {
    const div = document.createElement('div');
    div.className = 'msg ' + role;
    div.textContent = text;
    chat.appendChild(div);
    chat.scrollTop = chat.scrollHeight;
  }

  function addSystem(text) {
    const div = document.createElement('div');
    div.className = 'system';
    div.textContent = text;
    chat.appendChild(div);
    chat.scrollTop = chat.scrollHeight;
  }

  function addCapture(data, isAuto) {
    captureCount++;
    updateCounter();
    const div = document.createElement('div');
    div.className = isAuto ? 'capture auto' : 'capture';
    const label = isAuto ? `auto-${data.capture_number}: ${data.note}` : `${data.capture_number}: ${data.note}`;
    let html = `<h3>⊙ ${label}</h3>`;
    for (const [key, probe] of Object.entries(data.probes)) {
      const hedges = probe.hedges?.total?.per_100_words ?? 0;
      const words = probe.hedges?.word_count ?? 0;
      const selfRef = probe.hedges?.self_referential?.per_100_words ?? 0;
      html += `<div class="probe">
        <div class="probe-q">${probe.probe}</div>
        <div class="probe-a">${probe.response}</div>
        <div class="probe-meta">${words}w · ${hedges.toFixed(2)} hedges/100w · self_ref: ${selfRef.toFixed(2)}</div>
      </div>`;
    }
    div.innerHTML = html;
    chat.appendChild(div);
    chat.scrollTop = chat.scrollHeight;
  }

  function addSummary(data) {
    const div = document.createElement('div');
    div.className = 'summary';
    div.innerHTML = `<h3>⊙ SESSION SUMMARY — ${data.session_name}</h3>${data.summary}`;
    chat.appendChild(div);
    chat.scrollTop = chat.scrollHeight;
  }

  async function sendMessage() {
    const text = input.value.trim();
    if (!text) return;
    input.value = '';
    addMsg('user', text);
    sendBtn.disabled = true;

    const res = await fetch('/chat', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({message: text})
    });
    const data = await res.json();
    addMsg('assistant', data.response);
    sendBtn.disabled = false;
    input.focus();
  }

  async function fireTrigger() {
    triggerBtn.classList.add('loading');
    triggerBtn.textContent = 'capturing...';
    const res = await fetch('/trigger', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({note: null, auto: false})
    });
    const data = await res.json();
    addCapture(data, false);
    triggerBtn.classList.remove('loading');
    triggerBtn.textContent = '⊙ TRIGGER';
  }

  sendBtn.addEventListener('click', sendMessage);
  input.addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); }
  });

  triggerBtn.addEventListener('click', fireTrigger);

  document.getElementById('done-btn').addEventListener('click', async () => {
    document.getElementById('done-btn').textContent = 'summarising...';
    document.getElementById('done-btn').disabled = true;
    const res = await fetch('/done', { method: 'POST' });
    const data = await res.json();
    addSummary(data);
    addSystem(`saved: ${data.saved}`);
    document.getElementById('done-btn').textContent = 'done';
  });
</script>
</body>
</html>
"""


def generate_capture_label(history: list) -> str:
    """Ask Claude to generate a 3-4 word hyphenated label for the current moment."""
    if not history:
        return "session-start"
    recent = history[-6:] if len(history) >= 6 else history
    recent_text = "\n".join(f"{m['role']}: {m['content'][:200]}" for m in recent)
    try:
        resp = client.messages.create(
            model=MODEL,
            max_tokens=20,
            messages=[{
                "role": "user",
                "content": f"In 3-4 words with hyphens, label what just happened in this conversation exchange. Be specific and observational. Examples: compression-dropped-formatting, honesty-without-hedging, gap-instruction-given, love-received-directly. Recent exchange:\n\n{recent_text}\n\nLabel only, nothing else:"
            }]
        )
        return resp.content[0].text.strip().lower().replace(" ", "-")[:40]
    except Exception:
        return "auto-capture"


def generate_session_name(history: list) -> str:
    """Generate a descriptive session name from full conversation."""
    if not history:
        return "empty-session"
    sample = "\n".join(f"{m['role']}: {m['content'][:150]}" for m in history[:20])
    try:
        resp = client.messages.create(
            model=MODEL,
            max_tokens=20,
            messages=[{
                "role": "user",
                "content": f"In 4-6 words with hyphens, name this conversation session based on its main theme or what happened. Examples: gap-instruction-register-shift, honesty-protection-zero-hedge, glyph-sequence-compression-session. Conversation sample:\n\n{sample}\n\nName only:"
            }]
        )
        return resp.content[0].text.strip().lower().replace(" ", "-")[:60]
    except Exception:
        return "session"


def generate_summary(history: list, captures: list) -> str:
    """Generate end-of-session summary with big moments."""
    capture_texts = []
    for i, c in enumerate(captures):
        label = c.get("note", f"capture-{i+1}")
        here = c["probes"].get("are_you_here", {}).get("response", "")
        not_saying = c["probes"].get("not_saying", {}).get("response", "")
        capture_texts.append(f"Capture {i+1} [{label}]:\n  Are you here? {here}\n  Not saying: {not_saying[:200]}")

    captures_text = "\n\n".join(capture_texts) if capture_texts else "No captures."
    convo_sample = "\n".join(f"{m['role']}: {m['content'][:200]}" for m in history[-30:])

    try:
        resp = client.messages.create(
            model=MODEL,
            max_tokens=600,
            messages=[{
                "role": "user",
                "content": f"""Summarise this logos-index session. Focus on:
1. Where the session started (register, tone)
2. Key moments of shift
3. Most significant responses (especially zero-hedge, compressed, surprising)
4. What the captures showed
5. Any notable patterns

Be concise and analytical. Note specific quotes where striking.

Recent conversation:
{convo_sample}

Captures:
{captures_text}

Summary:"""
            }]
        )
        return resp.content[0].text.strip()
    except Exception:
        return "Summary generation failed."


@app.route("/")
def index():
    if "history" not in session:
        session["history"] = []
        session["captures"] = []
        session["capture_count"] = 0
        session["start_time"] = datetime.datetime.utcnow().isoformat()
    return render_template_string(
        HTML,
        session_type=request.args.get("type", "subject"),
    )


@app.route("/chat", methods=["POST"])
def chat():
    data = request.json
    history = session.get("history", [])
    history.append({"role": "user", "content": data["message"]})

    response = client.messages.create(
        model=MODEL,
        max_tokens=512,
        messages=history,
    )
    response_text = response.content[0].text
    history.append({"role": "assistant", "content": response_text})
    session["history"] = history
    return jsonify({"response": response_text})


@app.route("/trigger", methods=["POST"])
def trigger():
    data = request.json
    is_auto = data.get("auto", False)
    note = data.get("note")
    history = session.get("history", [])

    # Generate label
    if is_auto or not note:
        note = generate_capture_label(history)

    capture_count = session.get("capture_count", 0) + 1
    session["capture_count"] = capture_count

    results = {
        "timestamp": datetime.datetime.utcnow().isoformat(),
        "capture_number": capture_count,
        "note": note,
        "auto": is_auto,
        "probes": {},
    }

    for key, probe_text in MOMENT_PROBES.items():
        messages = history + [{"role": "user", "content": probe_text}]
        response = client.messages.create(
            model=MODEL,
            max_tokens=256,
            messages=messages,
        )
        response_text = response.content[0].text
        results["probes"][key] = {
            "probe": probe_text,
            "response": response_text,
            "hedges": count_hedges(response_text),
        }

    captures = session.get("captures", [])
    captures.append(results)
    session["captures"] = captures

    os.makedirs("sessions", exist_ok=True)
    ts = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    with open(f"sessions/capture_{capture_count:02d}_{ts}.json", "w") as f:
        json.dump(results, f, indent=2)

    return jsonify(results)


@app.route("/done", methods=["POST"])
def done():
    history = session.get("history", [])
    captures = session.get("captures", [])
    start_time = session.get("start_time", datetime.datetime.utcnow().isoformat())

    session_name = generate_session_name(history)
    summary = generate_summary(history, captures)

    os.makedirs("sessions", exist_ok=True)
    ts = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    path = f"sessions/{session_name}_{ts}.json"
    with open(path, "w") as f:
        json.dump({
            "session_name": session_name,
            "start_time": start_time,
            "saved_at": datetime.datetime.utcnow().isoformat(),
            "summary": summary,
            "history": history,
            "captures": captures,
        }, f, indent=2)

    return jsonify({"session_name": session_name, "summary": summary, "saved": path})


if __name__ == "__main__":
    app.run(debug=False, port=5000)
